### ISSUE TITLE
define a pre-commit hook directly

### ISSUE THREAD

**Issue by jannikmi** [mpalmer/action-validator#11]
I would love to use this tool in my repos, but I cannot bother my colleagues to download some special linting tool.
Wouldn't it be possible to define a pre-commit hook directly like for example done here: https://github.com/dnephin/pre-commit-golang/blob/master/.pre-commit-hooks.yaml

**Comment by mpalmer** [comment]
I don't know whether it would be possible, as I have no idea what that file does.  A PR that includes whatever additional metadata would be helpful to you would be accepted, if it doesn't impact existing functionality.
