### ISSUE TITLE
Automatically updating the schemas

### ISSUE THREAD

**Issue by rbozan** [mpalmer/action-validator#12]
It'd be nice if the schemas would be automatically updated. For example https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json is regularly updated but the schema within this crate does not. You could use something like a bot which would update it automatically or if you are more lazy, even using `git submodule` with schemastore repo would work or one of these solutions: https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository

**Comment by mpalmer** [comment]
Yes, the current method of including the schemas isn't great, but given that incorporating new schemas requires a rebuild, it's not necessarily just a matter of slapping in a submodule.  If you have a particular change to a schema that you need included, a PR to update the schema would be accepted, as would a suitable PR to automatically send PRs on update to the upstream schemas, if you're feeling more energetic.
