### ISSUE TITLE
Allowing the software to be run properly on Rust

### ISSUE THREAD

**Issue by rbozan** [mpalmer/action-validator#13]
Looking at the code it's mostly intended for CLI but with just a few small tweaks any Rust crate could use this crate properly with proper `Error` handling. Now it just returns a boolean.

https://github.com/mpalmer/action-validator/blob/main/src/schemas.rs#L19-L24

**Comment by mpalmer** [comment]
A PR that doesn't impact existing functionality would be accepted.  I have no need for calling this functionality from other Rust code, so I have no intention of implementing this myself.
