### ISSUE TITLE
bash reports "cannot execute binary file" when trying to run action-validator_darwin_amd64 

### ISSUE THREAD

**Issue by MarkCallow** [mpalmer/action-validator#15]
I downloaded [action-validator_darwin_amd64](https://github.com/mpalmer/action-validator/releases/download/v0.1.2/action-validator_darwin_amd64) from Releases. According to Finder it is a "Document". Finder opens it in a text editor - after I've made GateKeeper happy to open it. I set the mode to 755 and put it in my path. Bash then reports the error in the issue subject and the `file` utility reports it is a data file.

How can I run this tool?

**Comment by mpalmer** [comment]
Looks OK to me:

```
$ file action-validator_darwin_amd64
action-validator_darwin_amd64: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

What is the size and md5sum of the file you've downloaded?  If it opens in a text editor, does it *look* like text?

**Comment by MarkCallow** [comment]
The size is 3.7Mb. The md5 sum is 5b0c8e029427b15b2341270e16c7470d.

I've just downloaded it again. The new file is also 3.7Mb. The md5 sum is ca250ab408477c41626b714a6726652b. Finder still shows this as a "Document" but `file` now says it is a Mach-O executable and I've been able to run it. It looks like some gremlins crept into the original download.

@mpalmer thanks for your reply.
