### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by abonander** [mpalmer/action-validator#18]
It would be a lot easier to use this tool if it was possible to just do `cargo install action-validator`.

**Comment by repi** [comment]
Would indeed be great!

**Comment by matthiasbeyer** [comment]
I am also interested in this, because I would like to use this in a github action.

**Comment by mpalmer** [comment]
As of `action-validator` v0.2.1, we are now [on crates.io](https://crates.io/crates/action-validator)!
