### ISSUE TITLE
Question: Does action-validator support passing multiple filenames as arguments?

### ISSUE THREAD

**Issue by airtonix** [mpalmer/action-validator#19]
I want to use action-validator in our [`lint-staged`](https://github.com/okonet/lint-staged#Configuration) setup that executes on precommit via husky.

the way lint-staged works is by: 
- defining globs to files
- associating those globs with a command to run against

it executes the command like so: 

```
the-command ./file ./file ./file ./file
```

Does action-validator support this?

**Comment by mpalmer** [comment]
No, although a PR to support that would be accepted.
