### ISSUE TITLE
Confusing variable name

### ISSUE THREAD

**Issue by mathew-fleisch** [mpalmer/action-validator#2]
Hey I just tried out this tool out. Neat!
One confusing bit when I first started was I didn't realize it was expecting a single file. It'd be nice to change the usage section in the help dialog to say something like `path-to-action-yaml` instead of `<src>` to make that more explicit. I have never coded in rust before, and I can't see where to make this change.

```
action-validator
error: The following required arguments were not provided:
    <src>

USAGE:
    action-validator [FLAGS] <src>

For more information try --help
```

to something like

```
action-validator
error: The following required arguments were not provided:
    <src>

USAGE:
    action-validator [FLAGS] <path_to_action_file>

For more information try --help
```

**Comment by mpalmer** [comment]
Yep, that's a fair call.  Isn't tricky to fix.

**Comment by mpalmer** [comment]
Builds for v0.1.1 should be out in the next few minutes in the Releases, which expands the variable name to something less... terse.

**Comment by mathew-fleisch** [comment]
thanks!
