### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by bcheidemann** [mpalmer/action-validator#25]
Hi,

Do you have any interest in distributing this as a WASM / NPM package?

I already did most of the work for this and published it to NPM ([@bcheidemann/action-validator](https://www.npmjs.com/package/@bcheidemann/action-validator)) but I'm happy to upstream it into this project 🙂

Mostly what remains is to merge a PR I raised to Valico for adding WASM support, exposeing errors as a JSValue, and maybe a bit of tidy up.

**Comment by bcheidemann** [comment]
Update, [valico PR](https://github.com/s-panferov/valico/pull/87) is merged

**Comment by mpalmer** [comment]
Oh, that's neat!  I've never dipped my toe into WASM/NPM, so it wasn't on my radar, but I'm not against upstreaming this.  Looking at your branch, it'd be nice if the standard test suite could be run in either "native" or "node" mode, and the build/test jobs in the QA workflow modified to ensure that the WASM support stays "fresh".  Also, presumably a new job in the release workflow will be needed, to make releases to NPM alongside the native binaries and crate.  If you throw up your branch as a PR, we can go through the dance to get it merged in.
