### ISSUE TITLE
Release v0.4.0 Doesn't work with pre-commit - `.pre-commit-hooks.yaml is not a file`

### ISSUE THREAD

**Issue by award28** [mpalmer/action-validator#35]
It looks like the `.pre-commit-hooks.yaml` file is not included with Release [v0.4.0](https://github.com/mpalmer/action-validator/releases/tag/v0.4.0). Would you be able to cut a release for v0.4.1 to include this file?

It _looks_ like it was supposed to be included with the release based on [this comment](https://github.com/mpalmer/action-validator/pull/32#pullrequestreview-1320686528). However, I may be misreading this, and that comment indicates that it will ship in the next minor release. Would love to use this in pre-commit, but please close if that's the case!

**Comment by award28** [comment]
Good call - it needs to be updated to version `v0.4.1`. I can update this in PR #36.

**Comment by mpalmer** [comment]
So `rev: main` won't work?  It would be a *major* annoyance if I've got to bump a YAML file on (before?) every release just to keep `pre-commit` happy.

**Comment by award28** [comment]
Hmm I don't think I follow. I can download the release tagged v0.4.0 to double check, but the `pre-commit-hooks.yaml` file simply wasn't included in the release (at least, thats what pre commit was complaining about.)

I think the only thing that needs to happen is to cut a release of main after making the binary executable. Then pre commit can find the hooks file and execute the entry script.

**Comment by award28** [comment]
Yeah I just downloaded the latest version and the `pre-commit-hooks.yaml` file is missing. You won't need to bump the yaml file for each release - it just wasn't included with the last one.

<img width="218" alt="Screenshot 2023-03-07 at 12 08 10 PM" src="https://user-images.githubusercontent.com/10898929/223496311-91cfcb3d-3cee-4888-aae9-821d6f6e1d66.png">

**Comment by mpalmer** [comment]
I released as 0.5.0, because the release also includes removal of an (experimental) feature, so a patch release seemed inappropriate.  I've also bumped the README to refer to `rev: 0.5.0`, so :crossed_fingers: everything works now.

**Comment by award28** [comment]
Awesome, thank you Matt!

**Comment by award28** [comment]
I re-opened #36 and updated the recommended pre-commit version to `0.5.1`.
