### ISSUE TITLE
Using run-name property throws an error

### ISSUE THREAD

**Issue by DilepDev** [mpalmer/action-validator#49]
When using [run-name](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name) it throws "Additional property 'run-name' is not allowed"

**Error:**

```
Run find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
Treating .github/workflows/learn-github-actions.yml as a Workflow definition
Validation failed: ValidationState {
    errors: [
        Properties {
            path: "",
            detail: "Additional property 'run-name' is not allowed",
        },
    ],
    missing: [],
    replacement: None,
}
Fatal error validating .github/workflows/learn-github-actions.yml: validation failed
Treating .github/workflows/github-validate-yaml.yml as a Workflow definition
Validation failed: ValidationState {
    errors: [
        Properties {
            path: "",
            detail: "Additional property 'run-name' is not allowed",
        },
Fatal error validating .github/workflows/github-validate-yaml.yml: validation failed
    ],
    missing: [],
    replacement: None,
}
```

**Comment by mpalmer** [comment]
I can't reproduce this error.  When I add `run-name` as a top-level property in a workflow, it is accepted by `action-validator`.  Can you provide the version of `action-validator` you're using, and an example workflow file that is accepted by GitHub Actions?

**Comment by DilepDev** [comment]
I'll have this closed @mpalmer, I'm not able to reproduce this, I had it resolved it some how (can't remember how).
I'll Reopen the issue if it is experienced again
