### ISSUE TITLE
arm64 binary is unusable and is actually x86_64

### ISSUE THREAD

**Issue by deviantintegral** [mpalmer/action-validator#52]
```console
$ curl -L https://github.com/mpalmer/action-validator/releases/download/v0.5.1/action-validator_linux_arm64 -o action-validator
$ file action-validator
action-validator: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d6d20a546b16d7ce1bd43750a3f65970b5f1639a, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Note `x86-64` in the output above.

Unfortunately, the file doesn't execute correctly under emulation. I downloaded the amd64 version of [task](https://taskfile.dev) to compare, and we can see action-validator has an interpreter specified that's not actually available on my system.

```
$ file ./task
./task: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=PwnSGD9bn5MncgAbZgX4/aP32reofxPRUA_ZEUbQV/YnA4qqIfxJTViNfu2IpM/88pd3_evUfC0Tnyng9fL, stripped
```

Installing via npx works, but I think that's because it's using a `wasm` variant of the project builds. Unfortunately, npx itself is very slow so being able to install a single binary would be good improvement.

https://github.com/Lullabot/drainpipe/issues/220

**Comment by mpalmer** [comment]
What the whaaaaaaaaaaaaaaaaaaaaaaat?  I'll bet I left out a variable somewhere in the release workflow...

**Comment by mpalmer** [comment]
OK, v0.5.2 is now released, and the binaries linked to on the releases page appear to be for the correct architecture now.  Let me know if they don't actually work on a machine of the appropriate architecture.

**Comment by deviantintegral** [comment]
They work fine on my mac with colima. Thank you!
