### ISSUE TITLE
(feature request) pre-commit hook 

### ISSUE THREAD

**Issue by ygworldr** [mpalmer/action-validator#6]
Would it be possible to add a [pre-commit](https://pre-commit.com/) hook for this? [Link to documentation as to how to add new hooks](https://pre-commit.com/#new-hooks) if that helps…

Thank you!

**Comment by mpalmer** [comment]
A PR would be welcome.

**Comment by ygworldr** [comment]
> A PR would be welcome.

:100: would do it if I had the time. I'll try to but I have a lot on my plate (and I never did it before!) so it might take some time.
