### ISSUE TITLE
pre-commit hook should not require action-validator to be already installed or have an extra script

### ISSUE THREAD

**Issue by andrewring** [mpalmer/action-validator#74]
Hooks for the pre-commit tool are generally meant to be self contained. Current the hook in this repo require to have installed action-validator in the environment the pre-commit is being run prior to running the hook. To be more standard, the hook should use the [rust language option](https://pre-commit.com/#rust) in pre-commit. This will also require adding the more human friendly output, currently listed in a bash script, from the tool itself.

**Comment by mpalmer** [comment]
I don't use pre-commit myself, so anyone who wants this fixed will need to submit a PR.

**Comment by khaeru** [comment]
@glatterf42 and I just ran into this. Neither of us has any meaningful experience with Rust, but I did look at the [documentation for pre-commit itself](https://pre-commit.com/#rust) which says:

> Hook repositories must have a Cargo.toml file which produces at least one binary ([example](https://github.com/chriskuehl/example-rust-pre-commit-hook)), whose name should match the [entry](https://pre-commit.com/#hooks-entry) definition for your hook. The repo will be installed via cargo install --bins (with the binaries stored in your pre-commit cache, not polluting your user-level Cargo installations).
> …
> pre-commit will bootstrap rust if it is not present. language: rust also supports language_version
>
> Support: It has been tested on linux, Windows, and macOS.

I think these conditions are all met, so the changes could hopefully be very simple, like the linked example. I am not sure if we will get a chance to open a PR, but ofc. will link to this issue if we do.
