### ISSUE TITLE
WASM / node.js support broken with Rust nightly

### ISSUE THREAD

**Issue by mpalmer** [mpalmer/action-validator#78]
Per [this check run](https://github.com/mpalmer/action-validator/actions/runs/11943877740/job/33293767605), it looks like something in Rust nightly is unhappy with the current WASM support.  @award28 / @bcheidemann, are either of you able to take a look and fix it?  Otherwise, I'll probably just have to rip out all the WASM stuff, as I'm not able to maintain it myself.

**Comment by bcheidemann** [comment]
> Per [this check run](https://github.com/mpalmer/action-validator/actions/runs/11943877740/job/33293767605), it looks like something in Rust nightly is unhappy with the current WASM support.  @award28 / @bcheidemann, are either of you able to take a look and fix it?  Otherwise, I'll probably just have to rip out all the WASM stuff, as I'm not able to maintain it myself.

Hey @mpalmer,

Happy to take a look over the weekend 🙂 Currently we're just shy of 10k monthly downloads on NPM so  would be a shame to drop support as it's clearly useful for people!

**Comment by mpalmer** [comment]
Yeah, I don't want to rip it out either, but my supply of round tuits is perilously low, and it's not great having a perma-broken CI check...

**Comment by mpalmer** [comment]
There's a couple of other [issues tagged `nodejs`](https://github.com/mpalmer/action-validator/issues?q=is%3Aissue+is%3Aopen+label%3Anodejs), but they're not show-stoppers.  The only problem (other than this CI failure, which you've now tamed, yay!) related to WASM was in #76, where the difference in behaviour with the npm-provided executable (and lack of super-clear indication that it wasn't the native binary) caused some brief confusion, but we got it figured out.

Probably the biggest ongoing offence against my incipient OCD is the two open PRs, which are both WASM-related, but I avoid any problems by just not looking at them.  :grinning:

**Comment by bcheidemann** [comment]
> Probably the biggest ongoing offence against my incipient OCD is the two open PRs

Yeah, at this point I'm lacking a bit of context for those PRs, but I'll carve out some time to re-familiarise myself with them and try to get them over the line.

> There's a couple of other [issues tagged nodejs](https://github.com/mpalmer/action-validator/issues?q=is%3Aissue+is%3Aopen+label%3Anodejs), but they're not show-stoppers.

I'll check these out as well.

My own supply of round tuits is also a little lower than I'd like, but I'd like to allocate some of them to this project - only fair given I pushed for Node.js support in the first place! 🙂

**Comment by bcheidemann** [comment]
Leaving this here mostly for my own reference:

As per https://github.com/rustwasm/wasm-bindgen/issues/4283 the upstream cause of this issue is now fixed and we should be seeing a patch release soon in wasm-bindgen very soon. Once we have a patch release, we should be able to revert this change.

**Comment by bcheidemann** [comment]
@mpalmer as per the above comment #80 can now be reverted. I've tested on my local and raised https://github.com/mpalmer/action-validator/pull/81 to do so.
